#!/usr/bin/env python3
"""Regenerate the per-category problem tables and the top-level INDEX.md.

Reads the metadata header at the top of every solution file (format lives in
.claude/dsa/templates/cp.cpp) and rewrites only the region between the
BEGIN:INDEX / END:INDEX markers in each category README.md. Everything outside
those markers -- coverage checklist, prose, hand-written notes -- is preserved.

Usage:  python .claude/dsa/index.py           # rewrite indexes
        python .claude/dsa/index.py --check   # report only, touch nothing
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))

# Folders that get NOTES.md + README.md + a generated problem table.
CATEGORIES = [
    "DP",
    "Graph",
    "Data Structure",
    "Greedy",
    "Binary Search",
    "Two Pointers",
    "Bit Manipulation",
    "Number Theory",
    "Combinatorics",
    "String algorithm",
    "Geometry",
    "Constructive",
    "Game Theory",
    "LinkList",
]

# Kept for history but not indexed problem-by-problem: they predate the harness
# or are not topic-organised. Counted in INDEX.md, no table.
ARCHIVES = {
    "Codeforces": "Pre-harness dump, flat per judge. Not categorised.",
    "SRBD Code Contest 2024": "Contest-specific, kept as-is.",
    "python_programm": "Simulation/statistics coursework, not DSA practice.",
}

SKIP_DIRS = {".git", ".cph", ".vscode", "output", ".claude"}
SKIP_EXT = {".exe", ".bin", ".class", ".o", ".obj", ".txt", ".json", ".md"}
SKIP_NAMES = {"cp.cpp", "test.cpp"}

BEGIN = "<!-- BEGIN:INDEX (generated by .claude/dsa/index.py) -->"
END = "<!-- END:INDEX -->"

FIELDS = ("Problem", "Judge", "Link", "Category", "Technique",
          "Difficulty", "Status", "Insight", "Date")

# matches " * Problem   : foo" and "// Problem : foo" and "# Problem : foo"
FIELD_RE = re.compile(
    r"^\s*(?:\*|//+|#)\s*(" + "|".join(FIELDS) + r")\s*:\s*(.*?)\s*$")

STATUS_MARK = {
    "solved": "solved",
    "hint": "hint",
    "editorial": "editorial",
    "unsolved": "**unsolved**",
    "revisit": "**revisit**",
}


def is_solution(name):
    if name in SKIP_NAMES or name.startswith("."):
        return False
    return os.path.splitext(name)[1].lower() not in SKIP_EXT


def parse_header(path):
    """Pull the metadata block out of the first 30 lines. No block -> {}."""
    meta = {}
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            for i, line in enumerate(fh):
                if i > 30:
                    break
                m = FIELD_RE.match(line)
                if m:
                    meta[m.group(1)] = m.group(2)
    except OSError:
        pass
    return meta


def collect(category):
    """Every solution file under a category, paired with its metadata."""
    base = os.path.join(ROOT, category)
    rows = []
    if not os.path.isdir(base):
        return rows
    for dirpath, dirnames, filenames in os.walk(base):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for name in sorted(filenames):
            if not is_solution(name):
                continue
            full = os.path.join(dirpath, name)
            rel = os.path.relpath(full, base).replace("\\", "/")
            rows.append((rel, parse_header(full)))
    return rows


def md_link(text, target):
    """Markdown link, escaping what would otherwise break the link or table."""
    target = target.replace(" ", "%20").replace("(", "%28").replace(")", "%29")
    text = text.replace("|", "\\|").replace("[", "").replace("]", "")
    return "[" + text + "](" + target + ")"


def build_table(rows):
    if not rows:
        return ["_No problems logged yet._", "",
                "Add one with `/dsa-add <problem url>`."]

    logged = [r for r in rows if r[1].get("Problem")]
    bare = [r for r in rows if not r[1].get("Problem")]

    out = []
    if logged:
        out = ["| # | Problem | Judge | Technique | Status |",
               "|--:|---------|-------|-----------|--------|"]
    else:
        out = ["_Nothing logged yet -- every file here predates the harness._"]
    for i, (rel, meta) in enumerate(logged, 1):
        name = meta.get("Problem") or rel
        link = (meta.get("Link") or "").strip()
        title = md_link(name, link) if link.startswith("http") else name
        raw = (meta.get("Status") or "").strip()
        out.append("| %d | %s<br>%s | %s | %s | %s |" % (
            i, title, md_link(rel, rel),
            meta.get("Judge") or "-",
            meta.get("Technique") or "-",
            STATUS_MARK.get(raw, raw or "-")))

    out += ["", "%d logged" % len(logged)]
    if bare:
        out[-1] += ", %d with no metadata header" % len(bare)
        out += ["",
                "<details><summary>Files with no header yet "
                "(these predate the harness)</summary>", ""]
        out += ["- " + md_link(rel, rel) for rel, _ in bare]
        out += ["", "</details>"]
    return out


def splice(path, body, title):
    """Replace the marked region in path, creating the file if it is absent."""
    block = BEGIN + "\n\n" + "\n".join(body) + "\n\n" + END
    if os.path.isfile(path):
        with open(path, "r", encoding="utf-8") as fh:
            text = fh.read()
        if BEGIN in text and END in text:
            head, rest = text.split(BEGIN, 1)
            _, tail = rest.split(END, 1)
            return head + block + tail
        return text.rstrip() + "\n\n" + block + "\n"
    return ("# %s - Problem Index\n\nConcepts and intuition: "
            "[NOTES.md](NOTES.md).\n\n%s\n" % (title, block))


def write(path, text, check):
    old = None
    if os.path.isfile(path):
        with open(path, "r", encoding="utf-8") as fh:
            old = fh.read()
    if old == text:
        return False
    if not check:
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
    return True


def count_concepts(notes):
    """Number of '## ' headings in a NOTES.md, minus the boilerplate ones."""
    if not os.path.isfile(notes):
        return 0
    skip = ("## Index", "## How to use", "## Still to write up")
    n = 0
    with open(notes, "r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            if line.startswith("## ") and not line.startswith(skip):
                n += 1
    return n


def main():
    check = "--check" in sys.argv
    changed = []
    summary = []

    for category in CATEGORIES:
        base = os.path.join(ROOT, category)
        if not os.path.isdir(base):
            summary.append((category, None, 0))
            continue
        rows = collect(category)
        logged = sum(1 for _, m in rows if m.get("Problem"))
        readme = os.path.join(base, "README.md")
        if write(readme, splice(readme, build_table(rows), category), check):
            changed.append(category + "/README.md")
        summary.append((category, (len(rows), logged),
                        count_concepts(os.path.join(base, "NOTES.md"))))

    body = ["| Category | Files | Logged | Concepts | |",
            "|----------|------:|-------:|---------:|-|"]
    total = tlogged = tconcepts = 0
    for category, counts, concepts in summary:
        if counts is None:
            body.append("| %s | - | - | - | _not started_ |" % category)
            continue
        n, logged = counts
        total, tlogged, tconcepts = total + n, tlogged + logged, tconcepts + concepts
        body.append("| %s | %d | %d | %d | %s |" % (
            md_link(category, category + "/README.md"), n, logged, concepts,
            md_link("notes", category + "/NOTES.md")))
    body.append("| **Total** | **%d** | **%d** | **%d** | |"
                % (total, tlogged, tconcepts))

    body += ["", "### Archives (kept for history, not indexed)", "",
             "| Folder | Files | Why it is not a category |",
             "|--------|------:|--------------------------|"]
    for name, why in ARCHIVES.items():
        body.append("| %s | %d | %s |" % (name, len(collect(name)), why))

    index = os.path.join(ROOT, "INDEX.md")
    if write(index, splice(index, body, "DSA Practice"), check):
        changed.append("INDEX.md")

    if check:
        print("would rewrite: " + (", ".join(changed) or "nothing"))
    else:
        print("rewrote %d file(s)" % len(changed))
        for c in changed:
            print("  " + c)
    print("%d files, %d logged, %d concepts" % (total, tlogged, tconcepts))


if __name__ == "__main__":
    main()
